"""Draw the step 3 figure from data/results_local.json.

Writes docs/step3_figure.html, which scripts/render_docs_png.py turns into a PNG
the same way it does the other two pictures. The numbers are read from the
results file rather than typed in, so the figure cannot drift from the run.

Horizontal bars because the category labels are phrases. One hue throughout:
these five bars are one series and identity is carried by position and by the
label on every bar, so colour is not asked to name anything. The proposed
setting is the full-strength step, the baselines a lighter step of the same hue,
and the oracle is hatched because it is not a thing anyone is allowed to do.

Usage:
    uv run python scripts/plot_step3.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIGURE = ROOT / "docs" / "step3_figure.html"

# Two steps of one hue, checked against the chart surface rather than chosen by
# eye: L 0.695 and 0.481, delta L 0.214 against an ordinal minimum of 0.06, and
# the lighter step reaches 2.52:1 on #faf9f5 against a floor of 2.0. That is
# under the 3:1 categorical minimum, which obliges a visible label on every
# mark; every bar carries its value.
MUTED, FULL, INK, MUTED_INK, SURFACE = "#8CA86A", "#3B6D11", "#2c2c2a", "#5f5e5a", "#faf9f5"

# key in results_local.json -> (label, second line)
EVIDENCE = [
    ("scores_only", "no frequency at all", "the 12 scores alone"),
    ("public", "public reference", "what every hospital has today"),
    ("own_hospital", "own hospital only", "Oslo asking its own patients"),
    ("federated_query", "federated counts", "all three hospitals, counts only"),
    ("ceiling", "gnomAD oracle", "not allowed in real life"),
]


def bar(x: float, y: float, width: float, height: float, radius: float = 4) -> str:
    """A bar with its far end rounded and its baseline square."""
    radius = min(radius, width)
    return (f'M{x},{y} H{x + width - radius} A{radius},{radius} 0 0 1 {x + width},{y + radius} '
            f'V{y + height - radius} A{radius},{radius} 0 0 1 {x + width - radius},{y + height} H{x} Z')


def panel(title: str, note: str, values: dict[str, float], top: float, axis_max: float, fmt: str) -> str:
    """One panel of five horizontal bars sharing a single axis."""
    label_width, plot_left, plot_width, row_height, bar_height = 218.0, 228.0, 356.0, 34.0, 18.0
    out = [f'<text x="0" y="{top}" class="panel">{title}</text>',
           f'<text x="0" y="{top + 17}" class="note">{note}</text>']

    # Recessive gridlines, behind the marks.
    baseline = top + 30
    for step in range(5):
        x = plot_left + plot_width * step / 4
        out.append(f'<line x1="{x}" y1="{baseline}" x2="{x}" y2="{baseline + row_height * 5}" class="grid"/>')
        out.append(f'<text x="{x}" y="{baseline + row_height * 5 + 13}" class="tick">'
                   f'{axis_max * step / 4:{fmt}}</text>'.replace('class="tick"', 'text-anchor="middle" class="tick"'))

    for row, (key, label, sub) in enumerate(EVIDENCE):
        value = values[key]
        y = baseline + row * row_height + (row_height - bar_height) / 2
        width = max(1.5, plot_width * value / axis_max)
        is_oracle, is_method = key == "ceiling", key == "federated_query"
        fill = f'url(#hatch)' if is_oracle else (FULL if is_method else MUTED)
        edge = f' stroke="{FULL}" stroke-width="1.5"' if is_oracle else ""
        # text-anchor must be an ATTRIBUTE: WeasyPrint ignores it as a CSS property,
        # and every label silently lands on top of the bars.
        out.append(f'<g><title>{label}: {value:{fmt}}</title>'
                   f'<path d="{bar(plot_left, y, width, bar_height)}" fill="{fill}"{edge}/></g>')
        out.append(f'<text x="{label_width}" y="{y + 7}" text-anchor="end" '
                   f'class="cat{" strong" if is_method else ""}">{label}</text>')
        out.append(f'<text x="{label_width}" y="{y + 18}" text-anchor="end" class="sub">{sub}</text>')
        out.append(f'<text x="{plot_left + width + 7}" y="{y + 13}" class="value">{value:{fmt}}</text>')
    return "\n".join(out)


def main() -> int:
    results = json.loads((ROOT / "data" / "results_local.json").read_text())
    ablation, pooled = results["ablation"], results["evidence"]

    auc = {key: pooled["AUC, all test rows"]["pooled"][key] for key, _, _ in EVIDENCE if key != "scores_only"}
    auc["scores_only"] = ablation["scores_only"]["auc"]

    discordant = results["false_alarm_counts"]
    total = results["discordant_benign_rows"]

    figure = f"""<!DOCTYPE html>
<!--
  Step 3 figure. Generated by scripts/plot_step3.py from data/results_local.json,
  so do not edit the numbers here; rerun the script. Render to PNG with:

  uv run --with weasyprint --with pypdfium2 --with pillow python scripts/render_docs_png.py
-->
<html lang="en">
<head>
<meta charset="utf-8">
<title>Step 3: what frequency evidence buys</title>
<style>
  body{{margin:0;background:{SURFACE};color:{INK};font-family:-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}}
  .page{{width:680px;margin:0 auto;padding:24px 12px}}
  h1{{font-size:18px;font-weight:500;margin:0 0 3px}}
  .lede{{font-size:12px;color:{MUTED_INK};margin:0 0 4px;line-height:1.5}}
  .panel{{font-size:13px;font-weight:500;fill:{INK}}}
  .note{{font-size:10.5px;fill:{MUTED_INK}}}
  .cat{{font-size:11.5px;fill:{INK};text-anchor:end}}
  .cat.strong{{font-weight:500}}
  .sub{{font-size:9.5px;fill:{MUTED_INK};text-anchor:end}}
  .value{{font-size:11px;fill:{INK};font-family:ui-monospace,Menlo,Consolas,monospace}}
  .tick{{font-size:9.5px;fill:{MUTED_INK};text-anchor:middle;font-family:ui-monospace,Menlo,Consolas,monospace}}
  .grid{{stroke:#d9d7cf;stroke-width:1}}
  .caption{{font-size:11px;color:{MUTED_INK};margin:10px 0 0;line-height:1.55}}
  .caption b{{color:{INK};font-weight:500}}
</style>
</head>
<body>
<div class="page">
<h1>What the frequency evidence buys</h1>
<p class="lede">One logistic regression, trained once on the three hospitals' rows pooled.
The only thing that changes between bars is the answer it is given to &ldquo;how common is
this variant&rdquo;. Locked test set, {results["test_rows"]} variants.</p>

<svg width="680" height="470" role="img"
     aria-label="Two panels. AUC is flat across all five evidence settings, between 0.971 and 0.981. False alarms on the discordant benign rows fall from 15 with no frequency, to 7 with the public reference, 11 with the own hospital only, and 2 with federated counts, matching the gnomAD oracle at 2.">
  <defs>
    <pattern id="hatch" width="6" height="6" patternTransform="rotate(45)" patternUnits="userSpaceOnUse">
      <rect width="6" height="6" fill="{SURFACE}"/>
      <line x1="0" y1="0" x2="0" y2="6" stroke="{FULL}" stroke-width="3"/>
    </pattern>
  </defs>
{panel("Ranking: AUC on the whole test set", "higher is better &middot; the metric cannot see the difference", auc, 18, 1.0, ".3f")}
{panel(f"Decision: false alarms among the {total} population-discordant benign variants",
       "lower is better &middot; same model, same threshold, same variants", discordant, 258, 16, ".0f")}
</svg>

<p class="caption">Both panels, one model, one threshold, one test set. <b>AUC moves by 0.007
and would be invisible on any plot; false alarms fall sevenfold.</b> Frequency does not
reorder variants, it vetoes a few &mdash; the ones a hospital would otherwise call
disease-causing in a patient whose ancestry it rarely sees. A ranking metric is
structurally unable to show this, which is why the README section 5 grid reports both.</p>
<p class="caption">Federated counts land exactly on the oracle, so exchanging counts loses
nothing against being handed gnomAD's real per-population frequencies. A hospital asking
only its own patients does <b>worse</b> than today's public reference, because its cohort is
a third the size of gnomAD's European set: the gain comes from combining, not from being local.
Sensitivity on the {results["pathogenic_test_rows"]} pathogenic test rows stays at 0.92 in every
bar, so none of this is bought by missing disease-causing variants.</p>
<p class="caption"><b>&ldquo;Federated counts&rdquo; here is the step 6 query</b>, each hospital returning
carrier counts at scoring time. It is not FedAvg and no NVFlare is involved; federated
<i>training</i> is step 4 and is not built yet. Every model in this figure was trained locally.</p>
</div>
</body>
</html>
"""
    FIGURE.write_text(figure, encoding="utf-8")
    print(f"wrote {FIGURE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
